import type { Metadata } from 'next';
import { HeroProvider } from './HeroProvider.js';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const isDev = process.env.NODE_ENV === 'development';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeroProvider>{children}</HeroProvider>
      </body>
    </html>
  );
}
