import type { Metadata } from 'next';
import { HeroProvider } from './HeroProvider.js';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeroProvider>{children}</HeroProvider>
      </body>
    </html>
  );
}
