name: github pages

on:
  push:
    branches: 
      - main  # Set a branch name to trigger deployment
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'website/**'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Install Dependencies
        run: yarn --frozen-lockfile

      - name: Unit tests
        run: |
          yarn test

      - name: Build component
        run: |
          yarn build

      - name: Build website
        run: |
          yarn build-website  

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/out